title: "Glossa Contact Lab"
description: "Language Contact Research Laboratory"
baseurl: "/GlossaContactLab"
url: "https://athdgc.github.io"

# Keep private during development
future: false
show_drafts: false
